# Generated by Django 5.0.5 on 2024-05-10 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(max_length=100, verbose_name='Nombre del deudor')),
                ('description', models.TextField(max_length=500, verbose_name='Descripcion adicional')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la deuda')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creaicon')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID del usuario')),
            ],
            options={
                'verbose_name': 'Deudor',
                'verbose_name_plural': 'Deudores',
                'db_table': 'Deudores',
            },
        ),
    ]
