# Generated by Django 5.0.5 on 2024-05-12 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del ingreso')),
                ('source', models.CharField(max_length=50, verbose_name='Fuente de ingreso')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descripcion del prestamo')),
                ('date_of_registration', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del registro')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID del usuairo')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'Ingresos',
            },
        ),
    ]
