# Generated by Django 5.0.5 on 2024-05-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_expense_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.TextField(max_length=50, verbose_name='Titulo del gasto'),
        ),
    ]
