# Generated by Django 5.0.5 on 2024-05-11 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lender', models.CharField(max_length=50, verbose_name='Prestamista')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del prestamo')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Descripcion del prestamo')),
                ('date_of_registration', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del registro')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ID del usuairo')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
                'db_table': 'Prestamos',
            },
        ),
    ]
